background = "#1a1110"
foreground = "#f1dedc"
color1 = "#ffb4ab"
color2 = "#dfc38c"
color3 = "#574419"
color4 = "#ffb4a9"
color5 = "#e7bdb7"
color6 = "#ffb4a9"
color7 = "#d8c2be"
color8 = "#322826"
accent  = "#ffb4a9"
