background = "#18130b"
foreground = "#ece1d4"
color1 = "#ffb4ab"
color2 = "#b6cea3"
color3 = "#384c2c"
color4 = "#f1be6d"
color5 = "#dcc3a1"
color6 = "#f1be6d"
color7 = "#d2c4b4"
color8 = "#2f2921"
accent  = "#f1be6d"
